sudo: false  
language: java    
jdk:
  - oraclejdk8
cache:  
  directories:  
   - $HOME/.m2
before_install: ./setup_travis.sh
script: "./mvnw verify"
deploy:
  skip_cleanup: true
  provider: bintray
  file: "deploy.json"
  user: 
      secure: "D6JcC/42SBstqRD5nTPLTUSY5JIYexsS1Q5dH4x9EWM3DWN1yvW033VnkcAhhziOU9FUJDnuhWSvcia5MkgJL9BbXpfx3SzV54VeSmgpCzXyeUotBgRlZx/+FjNppJMyNG6CvOw17uXiceA9qQoku65JVDi/o9VyPYI/uwDGMTh5Liv1epoVkOovoBsCAgGUlQ2TFRo9UyLUydxzRBM6wt1ucBmuui71lt4yxarloIMXLTLL3WLatJNJdhbLFJBGU61GU9jVS1ZiJ8pB48LMZHcnJiWsfF4E26NBV4Jlf7U2vTVcJaAS2Vy/4vjSoHhLxobtialJNfBjwA4VpQNlfQ0Q3aan+Dx/xSUTvGTcVxQgu19I9nfp80UQ+52a9o6qjWADMV9PpbVHbRWQIyC5/YyUrxDE/gtLOrJHbmr20POoLlMY2XqLcppX9viH+REyg9qRAUTUzChSIA/y9TlQqiMBtzCbK3db5aHi7n+ghiYyceXFqfIn3fIsSWfPv7uqXcZ6xFM1i+5pFt1nlTkENUMFBRAIAUoh25zUEbcDCs+AZHjBXrbJdK/+Fhjm4QawQOVeQVc/T4yCogkDc4Pk4P33TXBd/whtrPRDuwkN1h9zFRwp0yCM5nINYmzmzAxGBz5hzH0zKHY9BFib4oOHu2QU00+61GIHG6bnRIl9HUY="
  key:
       secure: "0czK1uj+uMZRXfLChu87xm60kh1BAJ9Sej1ktMNX33xqFe52ya+dZNZKLJUT8yNGiMhI65fBD3Ek/nde2q23rDCK+sad3oVTLZ8L1hpHss81Fic4F8lRtlRWCxJeStPuirNUCWN9/WPx8ytJm40dIGlf9pzMkr3qx6GR1DiY09YxrKgUQrKrfCSP8HbSN6vk5orpwqaMMe9ZmDckakZP+HX7upj7cyYex058JQeE0Yv2uX68r4bBq5QR3YQMNYmKYbjufo01/pPXbJhSsPK07VoGyNWF0B+VkO1e6gj4h9QVQl+x6d6B9Wx/8qymfOmu3+i4a5UfPTuL27f16qS5APiex3Gcd5QH+QNxS7vPt+YoRWNzg/2Rqb6yqgIY7Gz1RUw9hwkCK41Icmum6+fH71kRjICxFgWrnOGxp4mryVwmT63tyBwQAvt46h4eqorthr6hAX6QEwfY14jRzIMFwrq/symQ8sySTPelyCGtrhHD1DIWIvuzN7YzNvecdZqSQa+YfjsvJkUOFmkqDVpYnWO0Tsj7E9xQaaZS4ZDGlei3/Jge6TT3zbhVkmAXShaQjBMc0jlEsrA0SQ5n51zea6D0o/5AnQ2UncXagqRjXA3ZvZVKxVgUudSsH3lAfD48zs8eI6rT0P75TnZPE48jzJ0IrNy9e4hm/p2WaTcBQ+U="
